// Copyright (C) 2007-2019  CEA/DEN, EDF R&D, OPEN CASCADE
//
// Copyright (C) 2003-2007  OPEN CASCADE, EADS/CCR, LIP6, CEA/DEN,
// CEDRAT, EDF R&D, LEG, PRINCIPIA R&D, BUREAU VERITAS
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
//
// See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
//

#ifndef __SHAPERSTUDY_GEN__
#define __SHAPERSTUDY_GEN__

#include "GEOM_Gen.idl"
#include "SALOMEDS.idl"
#include "SALOME_Exception.idl"

module SHAPERSTUDY_ORB
{

interface SHAPER_Object     : GEOM::GEOM_Object
{
  /*!
  *  \brief Puts the shape to the object by BRep stream.
  */
  void SetShapeByStream(in string theStream);
  /*!
  *  \brief Sets the internal entry of the object, common for all objects in SHAPER-STUDY
  */
  void SetEntry( in string theInternalEntry );
  /*!
  *  \brief Sets SObject of this object (when it is published)
  */
  void SetSO( in SALOMEDS::SObject theInternalEntry );
  /*!
  *  \brief Returns SObject of this object
  */
  SALOMEDS::SObject GetSO();

};

interface Gen : GEOM::GEOM_Gen
{
  /*!
   *  \brief Searches existing or creates a new SHAPERSTUDY_Object to interact with SHAPER
   */
  SHAPER_Object FindOrCreateShape(in string theInternalEntry);
};

interface IShapesOperations : GEOM::GEOM_IShapesOperations
{
};

interface IGroupOperations  : GEOM::GEOM_IGroupOperations
{
};

interface IFieldOperations  : GEOM::GEOM_IFieldOperations
{
};

interface IMeasureOperations  : GEOM::GEOM_IMeasureOperations
{
};

interface Field             : GEOM::GEOM_Field
{
};

interface FieldStep         : GEOM::GEOM_FieldStep
{
};

interface DoubleFieldStep   : GEOM::GEOM_DoubleFieldStep
{
};

interface IntFieldStep      : GEOM::GEOM_IntFieldStep
{
};

interface BoolFieldStep     : GEOM::GEOM_BoolFieldStep
{
};

};

#endif
